version:  '3.8'
services:
  php-apache:
    image: mcr.microsoft.com/vscode/devcontainers/php:8.1-apache
    ports:
      - 80:80
    volumes:
      - ../:/var/www/html
    depends_on:
        - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"


volumes:
  mysql-data:
    